g++Flags = -std="c++17" -Wall -Werror
rankFunctions = moreClassesInDay/stackRank.o afterTime/afterTime.o timeBetweenClasses/timeBetweenClasses.o

build: $(rankFunctions) rank.cpp rankFunctions.cpp
    g++ $(g++Flags) -c rank.cpp rankFunctions.cpp $(rankFunctions) -o rank.o


moreClassesInDay/stackRank.o: moreClassesInDay/stackRank.cpp moreClassesInDay/stackRank.hpp
    cd moreClassesInDay | make

afterTime/afterTime.o: afterTime/afterTime.cpp afterTime/afterTime.hpp
    cd afterTime | make

timeBetweenClasses/timeBetweenClasses.o: timeBetweenClasses/timeBetweenClasses.cpp timeBetweenClasses/timeBetweenClasses.hpp
    cd timeBetweenClasses | make

